### ISSUE TITLE
Upgrade to blade-icons 1.0

### ISSUE THREAD

**Issue by swapnilsarwe** [brunocfalcao/blade-jam-icons#1]
Hello @brunocfalcao ,

Are you still maintaining this package. If yes I can help in adding support for blade-icons 1.0.

Actually I created a repository (https://github.com/codeat3/blade-jam-icons) and while submitting to packagist, I came to know that similar thing already exist.

**Comment by brunocfalcao** [comment]
Hi there! Thanks for letting me know, actually I am not maintaining it, I started but never submitted it.

Feel free to move forward with your own repo, and thanks for letting me know.

Best,
Bruno
